[package]
name = "xplane"
version = "0.1.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.0"
rocket = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
xplm = "0.2"

[lib]
crate-type = ["cdylib"]